// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/snyk/cli-extension-sbom/internal/bundlestore (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../mocks/mock_bundlestore_client.go github.com/snyk/cli-extension-sbom/internal/bundlestore Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// UploadSBOM mocks base method.
func (m *MockClient) UploadSBOM(ctx context.Context, sbomPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadSBOM", ctx, sbomPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadSBOM indicates an expected call of UploadSBOM.
func (mr *MockClientMockRecorder) UploadSBOM(ctx, sbomPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadSBOM", reflect.TypeOf((*MockClient)(nil).UploadSBOM), ctx, sbomPath)
}

// UploadSourceCode mocks base method.
func (m *MockClient) UploadSourceCode(ctx context.Context, sourceCodePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadSourceCode", ctx, sourceCodePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadSourceCode indicates an expected call of UploadSourceCode.
func (mr *MockClientMockRecorder) UploadSourceCode(ctx, sourceCodePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadSourceCode", reflect.TypeOf((*MockClient)(nil).UploadSourceCode), ctx, sourceCodePath)
}
