run:
  build-tags:
    - integration
  concurrency: 4
  issues-exit-code: 1
  skip-dirs:
    - internal/mocks
  tests: true
  timeout: 5m

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true
  exhaustive:
    default-signifies-exhaustive: true
  goconst:
    ignore-calls: false
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 10
  goimports:
    local-prefixes: github.com/snyk/cli-extension-sbom
  gosimple:
    checks: ["all"]
  govet:
    check-shadowing: true
    disable:
      - fieldalignment
  lll:
    line-length: 160
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  promlinter:
    strict: true
  staticcheck:
    checks: ["all"]
  stylecheck:
    checks: ["all"]
    http-status-code-whitelist: []
  varcheck:
    exported-fields: true

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goimports
    - goprintffuncname
    - gosec
    - interfacebloat
    - ireturn
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
        - goconst
        - ireturn
