version: 2.1

orbs:
  go: circleci/go@1.7.1

jobs:
  unit-test:
    executor:
      name: go/default
      tag: '1.21'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
  lint:
    docker:
      - image: golangci/golangci-lint:v1.56.2-alpine
    steps:
      - checkout
      - run: golangci-lint run -v ./...

  security-scans:
    executor:
      name: go/default
      tag: '1.21'
    resource_class: small
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto
          iac-scan: disabled

workflows:
  version: 2
  CI:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: team-unify-alerts
          filters:
            branches:
              ignore:
                - main
      - security-scans:
          name: Security Scans
          context:
            - analysis_unify
      - unit-test:
          name: Unit Test
      - lint:
          name: Linting

