version: 2.1

orbs:
  go: circleci/go@1.7.1

jobs:
  Unit Tests:
    executor:
      name: go/default
      tag: '1.19'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
  Linting:
    docker:
      - image: golangci/golangci-lint:v1.50-alpine
    steps:
      - checkout
      - run: golangci-lint run -v ./...

workflows:
  CI:
    jobs:
      - Unit Tests
      - Linting
